algoritmo "A maior ou menor idade"
// Disciplina  : Algoritmos e Programação Estruturada
// Professor(a):
// Descrição   : A maior ou menor idade
// Autor(a)    : Lucas Bedatty
// Data atual  : 25/02/2024
var
   idade: Inteiro

inicio
   Escreva("Informe a sua idade: ")
   Leia(idade)

   Se idade >= 18 Entao
      Escreva("Maior de idade")
   Senao
      Escreva("Menor de idade")
   FimSe

fimalgoritmo